version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: hermes_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  hermes_net:
    driver: local

volumes:
  rabbitmq_data:
    driver: local
